gatsby.settings:
  type: config_object
  label: 'Gatsby settings'
  mapping:
    server_url:
      type: uri
      label: 'Server URL'
    path_mapping:
      type: string
      label: 'Path Mapping'
    incrementalbuild_url:
      type: uri
      label: 'Incrmental build URL'
    build_published:
      type: boolean
      label: 'Build published'
    preview_entity_types:
      type: sequence
      label: 'Preview Entity Types'
      sequence:
        type: string
